In [ ]:
import pandas as pd, numpy as np

In [ ]:
data = pd.read_csv("data.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 46 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   شماره دانشجویی           981 non-null    int64
 1   نوع مدرسه                84 non-null     object
 2   معدل دیپلم               89 non-null     float64
 3   کدملی                    981 non-null    object
 4   نام                      981 non-null    object
 5   نام‌خانوادگی             981 non-null    object
 6   وضعیت دانشجو             981 non-null    object
 7   نوع دوره پزشکی           978 non-null    object
 8   رشته تحصیلی              981 non-null    object
 9   ترم ورودی                981 non-null    int64
 10  معدل دوره علوم پایه      980 non-null    float64
 11  معدل دوره فیزیوپاتولوژی  979 non-null    float64
 12  معدل دوره بالینی         979 non-null    float64
 13  معدل دوره انترنی         981 non-null    float64
 14  13901                    92 non-null     float64
 15  13902                    143 non-null    float64
 16  13903                    43 non-null     float64
 17  13911                    233 non-null    float64
 18  13912                    287 non-null    float64
 19  13913                    44 non-null     float64
 20  13921                    379 non-null    float64
 21  13922                    423 non-null    float64
 22  13923                    83 non-null     float64
 23  13931                    506 non-null    float64
 24  13932                    483 non-null    float64
 25  13933                    25 non-null     float64
 26  13941                    538 non-null    float64
 27  13942                    530 non-null    float64
 28  13943                    35 non-null     float64
 29  13951                    556 non-null    float64
 30  13952                    520 non-null    float64
 31  13953                    11 non-null     float64
 32  13961                    541 non-null    float64
 33  13962                    483 non-null    float64
 34  13963                    11 non-null     float64
 35  13971                    423 non-null    float64
 36  13972                    351 non-null    float64
 37  13973                    15 non-null     float64
 38  13981                    281 non-null    float64
 39  13982                    187 non-null    float64
 40  13983                    0 non-null      float64
 41  13991                    126 non-null    float64
 42  13992                    42 non-null     float64
 43  13993                    0 non-null      float64
 44  14001                    3 non-null      float64
 45  14002                    2 non-null      float64
dtypes: float64(37), int64(2), object(7)
memory usage: 352.7+ KB

In [ ]:
data = data.drop(columns=['شماره دانشجویی', 'نوع مدرسه', 'کدملی', 'نام', 'نام‌خانوادگی','13903','13913','13933','13943','13953','13963','13973','13983','13993'])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

str_cols = ["وضعیت دانشجو", "نوع دوره پزشکی", "رشته تحصیلی"]  # String/categorical columns
encoder = OrdinalEncoder()
data[str_cols] = encoder.fit_transform(data[str_cols])

imputer = SimpleImputer(strategy="most_frequent")
data[str_cols] = pd.DataFrame(
    imputer.fit_transform(data[str_cols]),
    columns=data[str_cols].columns,
    index=data[str_cols].index
)

In [ ]:
import pandas as pd

# Retrieve the categories from the fitted encoder
mapping_dict = {}
for i, col in enumerate(str_cols):
    # The encoder stores categories in a list of arrays
    categories = encoder.categories_[i]
    # Create a dictionary where the index is the integer and the value is the original name
    mapping_dict[col] = {idx: label for idx, label in enumerate(categories)}

# Display the mappings clearly
for column, mapping in mapping_dict.items():
    print(f"--- Mapping for '{column}' ---")
    for integer_val, original_val in mapping.items():
        print(f"  {integer_val} -> {original_val}")
    print()

--- Mapping for 'وضعیت دانشجو' ---
  0 -> فارغ‌التحصیل

--- Mapping for 'نوع دوره پزشکی' ---
  0 -> انترنی
  1 -> بالینی
  2 -> nan

--- Mapping for 'رشته تحصیلی' ---
  0 -> پزشکی

In [ ]:
data.head()

,معدل دیپلم,وضعیت دانشجو,نوع دوره پزشکی,رشته تحصیلی,ترم ورودی,معدل دوره علوم پایه,معدل دوره فیزیوپاتولوژی,معدل دوره بالینی,معدل دوره انترنی,13901,...,13961,13962,13971,13972,13981,13982,13991,13992,14001,14002
0,19.71,0.0,1.0,0.0,13901,15.09,15.00,14.92,15.45,15.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19.72,0.0,1.0,0.0,13901,15.15,15.15,15.66,16.20,14.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19.93,0.0,1.0,0.0,13901,15.28,15.15,15.06,15.41,14.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19.66,0.0,1.0,0.0,13901,16.35,16.42,16.33,16.70,15.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19.06,0.0,1.0,0.0,13901,14.96,15.20,15.84,16.20,13.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data['ترم ورودی'] = data['ترم ورودی'].astype(str)
for i in range(7):
    globals()[f'data{i}'] = data[data['ترم ورودی'].str[-2] == str(i)]

In [ ]:
keep_numeric_for_data0 = ['13901', '13902', '13911', '13912', '13921', '13922', '13931']
data0 = data0[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13901', '13902', '13911', '13912', '13921', '13922', '13931']]
data1 = data1[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13941', '13911', '13912', '13921', '13922', '13931', '13932']]
data2 = data2[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13951', '13941', '13942', '13921', '13922', '13931', '13932']]
data3 = data3[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13961', '13951', '13952', '13941', '13942', '13931', '13932']]
data4 = data4[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13971', '13961', '13962', '13951', '13952', '13941', '13942']]
data5 = data5[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13981', '13971', '13972', '13961', '13962', '13951', '13952']]
data6 = data6[['معدل دیپلم','معدل دوره علوم پایه','معدل دوره فیزیوپاتولوژی','معدل دوره بالینی','معدل دوره انترنی', 'نوع دوره پزشکی', '13991', '13981', '13982', '13971', '13972', '13961', '13962']]

In [ ]:
data0.rename(columns={'13901':'11', '13902':'12', '13911':'21', '13912':'22', '13921':'31', '13922':'32', '13931':'41'}, inplace=True)
data1.rename(columns={'13911':'11', '13912':'12', '13921':'21', '13922':'22', '13931':'31', '13932':'32', '13941':'41'}, inplace=True)
data2.rename(columns={'13921':'11', '13922':'12', '13931':'21', '13932':'22', '13941':'31', '13942':'32', '13951':'41'}, inplace=True)
data3.rename(columns={'13931':'11', '13932':'12', '13941':'21', '13942':'22', '13951':'31', '13952':'32', '13961':'41'}, inplace=True)
data4.rename(columns={'13941':'11', '13942':'12', '13951':'21', '13952':'22', '13961':'31', '13962':'32', '13971':'41'}, inplace=True)
data5.rename(columns={'13951':'11', '13952':'12', '13961':'21', '13962':'22', '13971':'31', '13972':'32', '13981':'41'}, inplace=True)
data6.rename(columns={'13961':'11', '13962':'12', '13971':'21', '13972':'22', '13981':'31', '13982':'32', '13991':'41'}, inplace=True)

In [ ]:
data0.head()

,معدل دیپلم,معدل دوره علوم پایه,معدل دوره فیزیوپاتولوژی,معدل دوره بالینی,معدل دوره انترنی,نوع دوره پزشکی,11,12,21,22,31,32,41
0,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,14.97,NaN
1,19.72,15.15,15.15,15.66,16.20,1.0,14.05,14.91,15.20,15.22,15.20,15.02,15.15
2,19.93,15.28,15.15,15.06,15.41,1.0,14.56,15.02,15.63,15.32,15.16,15.12,NaN
3,19.66,16.35,16.42,16.33,16.70,1.0,15.59,16.10,16.43,16.26,16.37,16.32,16.42
4,19.06,14.96,15.20,15.84,16.20,1.0,13.35,13.56,14.38,14.77,14.94,15.01,15.20

In [ ]:
all_dataframes = [data0, data1, data2, data3, data4, data5, data6]
combined_data = pd.concat(all_dataframes, ignore_index=True)
print("Combined DataFrame created successfully. Here's a preview:")
display(combined_data.head())

Combined DataFrame created successfully. Here's a preview:

,معدل دیپلم,معدل دوره علوم پایه,معدل دوره فیزیوپاتولوژی,معدل دوره بالینی,معدل دوره انترنی,نوع دوره پزشکی,11,12,21,22,31,32,41
0,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,14.97,NaN
1,19.72,15.15,15.15,15.66,16.20,1.0,14.05,14.91,15.20,15.22,15.20,15.02,15.15
2,19.93,15.28,15.15,15.06,15.41,1.0,14.56,15.02,15.63,15.32,15.16,15.12,NaN
3,19.66,16.35,16.42,16.33,16.70,1.0,15.59,16.10,16.43,16.26,16.37,16.32,16.42
4,19.06,14.96,15.20,15.84,16.20,1.0,13.35,13.56,14.38,14.77,14.94,15.01,15.20

In [ ]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   معدل دیپلم               89 non-null     float64
 1   معدل دوره علوم پایه      980 non-null    float64
 2   معدل دوره فیزیوپاتولوژی  979 non-null    float64
 3   معدل دوره بالینی         979 non-null    float64
 4   معدل دوره انترنی         981 non-null    float64
 5   نوع دوره پزشکی           981 non-null    float64
 6   11                       644 non-null    float64
 7   12                       972 non-null    float64
 8   21                       971 non-null    float64
 9   22                       978 non-null    float64
 10  31                       973 non-null    float64
 11  32                       969 non-null    float64
 12  41                       955 non-null    float64
dtypes: float64(13)
memory usage: 99.8 KB

In [ ]:
columns_to_impute = ['11', '12', '21', '22', '31', '32', '41']

for col in columns_to_impute:
    if col in combined_data.columns:
        median_val = combined_data[col].median()
        combined_data[col].fillna(median_val, inplace=True)
combined_data=combined_data.dropna()
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 94
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   معدل دیپلم               89 non-null     float64
 1   معدل دوره علوم پایه      89 non-null     float64
 2   معدل دوره فیزیوپاتولوژی  89 non-null     float64
 3   معدل دوره بالینی         89 non-null     float64
 4   معدل دوره انترنی         89 non-null     float64
 5   نوع دوره پزشکی           89 non-null     float64
 6   11                       89 non-null     float64
 7   12                       89 non-null     float64
 8   21                       89 non-null     float64
 9   22                       89 non-null     float64
 10  31                       89 non-null     float64
 11  32                       89 non-null     float64
 12  41                       89 non-null     float64
dtypes: float64(13)
memory usage: 9.7 KB

/tmp/ipykernel_13582/2619269180.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_data[col].fillna(median_val, inplace=True)

In [ ]:
combined_data.head()

,معدل دیپلم,معدل دوره علوم پایه,معدل دوره فیزیوپاتولوژی,معدل دوره بالینی,معدل دوره انترنی,نوع دوره پزشکی,11,12,21,22,31,32,41
0,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,14.97,15.07
1,19.72,15.15,15.15,15.66,16.20,1.0,14.05,14.91,15.20,15.22,15.20,15.02,15.15
2,19.93,15.28,15.15,15.06,15.41,1.0,14.56,15.02,15.63,15.32,15.16,15.12,15.07
3,19.66,16.35,16.42,16.33,16.70,1.0,15.59,16.10,16.43,16.26,16.37,16.32,16.42
4,19.06,14.96,15.20,15.84,16.20,1.0,13.35,13.56,14.38,14.77,14.94,15.01,15.20

In [ ]:
x41_data = combined_data.drop(['41'], axis=1)
y41_data = combined_data[['41']]

x32_data = combined_data.drop(['32','41'], axis=1)
y32_data = combined_data[['32']]

x31_data = combined_data.drop(['31','32','41'], axis=1)
y31_data = combined_data[['31']]

x22_data = combined_data.drop(['22','31','32','41'], axis=1)
y22_data = combined_data[['22']]

x21_data = combined_data.drop(['21','22','31','32','41'], axis=1)
y21_data = combined_data[['21']]

x12_data = combined_data.drop(['12','21','22','31','32','41'], axis=1)
y12_data = combined_data[['12']]

In [ ]:
x12_data = x12_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x21_data = x21_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x12_data = x12_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x22_data = x22_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x31_data = x31_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x32_data = x32_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})
x41_data = x41_data.rename(columns={
    "عدل دیپلم": "diploma_avg",
    "معدل دوره علوم پایه": "basic_science_avg",
    "معدل دوره فیزیوپاتولوژی": "physiopathology_avg",
    "معدل دوره بالینی": "clinical_avg",
    "معدل دوره انترنی": "internship_avg",
    "نوع دوره پزشکی": "medical_course_type",
})

In [ ]:
!pip install onnx onnxmltools onnxruntime skl2onnx

Requirement already satisfied: onnx in /usr/local/lib/python3.12/dist-packages (1.21.0)
Requirement already satisfied: onnxmltools in /usr/local/lib/python3.12/dist-packages (1.16.0)
Requirement already satisfied: onnxruntime in /usr/local/lib/python3.12/dist-packages (1.26.0)
Requirement already satisfied: skl2onnx in /usr/local/lib/python3.12/dist-packages (1.20.0)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.12/dist-packages (from onnx) (2.0.2)
Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (5.29.6)
Requirement already satisfied: typing_extensions>=4.7.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx) (0.5.4)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (25.12.19)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from onnxruntime) (26.2)
Requirement already satisfied: scikit-learn>=1.1 in /usr/local/lib/python3.12/dist-packages (from skl2onnx) (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1->skl2onnx) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1->skl2onnx) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1->skl2onnx) (3.6.0)

In [ ]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import json
import onnx
import onnxmltools
from onnxmltools.convert.common.data_types import FloatTensorType
import matplotlib.pyplot as plt

# Optimized model for small dataset and wider prediction range
model = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.1,
    num_leaves=15,
    max_depth=5,
    min_child_samples=5,  # Important for small datasets
    boosting_type='gbdt',
    objective='regression',
    random_state=42,
    n_jobs=-1,
    importance_type='gain'
)

def run_model(x_data, y_data, num):
    x_train, x_val, y_train, y_val = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    x_train = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns, index=x_train.index)
    x_val = pd.DataFrame(scaler.transform(x_val), columns=x_val.columns, index=x_val.index)

    model.fit(
        x_train, y_train.values.ravel(),
        eval_set=[(x_val, y_val.values.ravel())],
        eval_metric='rmse',
        callbacks=[lgb.early_stopping(stopping_rounds=30), lgb.log_evaluation(period=0)]
    )

    # Check prediction range
    preds = model.predict(x_val)
    print(f"Model {num} - Actual Range: [{y_val.values.min():.2f}, {y_val.values.max():.2f}] - Predicted Range: [{preds.min():.2f}, {preds.max():.2f}]")

    scaling_params = {
        "mean": scaler.mean_.tolist(),
        "std": scaler.scale_.tolist(),
        "feature_names": x_train.columns.tolist()
    }
    with open(f"scaling_params{num}.json", "w") as f: json.dump(scaling_params, f)

    n_features = x_train.shape[1]
    initial_type = [('float_input', FloatTensorType([None, n_features]))]
    onnx_model = onnxmltools.convert_lightgbm(model, initial_types=initial_type, target_opset=12)
    onnx.save_model(onnx_model, f"LGBMModel{num}.onnx")

    return model, scaler

# Re-train models
for label, x_df, y_df in [
    (41, x41_data, y41_data), (32, x32_data, y32_data),
    (31, x31_data, y31_data), (22, x22_data, y22_data),
    (21, x21_data, y21_data), (12, x12_data, y12_data)
]:
    run_model(x_df, y_df, label)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002372 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 274
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 12
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.129859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[106]	valid_0's rmse: 0.192535	valid_0's l2: 0.0370698
Model 41 - Actual Range: [11.93, 17.64] - Predicted Range: [12.42, 17.38]
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000027 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 250
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 11
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.191831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[45]	valid_0's rmse: 0.214747	valid_0's l2: 0.0461161
Model 32 - Actual Range: [11.97, 17.67] - Predicted Range: [12.48, 17.33]
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000028 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 225
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 10
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.276620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def get_predictions_table(x_data, y_data, model_name):
    # Replicate the split used in training
    x_train, x_val, y_train, y_val = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

    # Scale x_val using a local scaler (matching training logic)
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_val_scaled = pd.DataFrame(scaler.transform(x_val), columns=x_val.columns, index=x_val.index)

    # Generate predictions
    preds = model.predict(x_val_scaled)

    # Create comparison table starting with features (x_val)
    results = x_val.copy().reset_index(drop=True)

    # Add target and predictions
    results['Actual_Score'] = y_val.values.flatten()
    results['Predicted_Score'] = preds
    results['Difference'] = results['Actual_Score'] - results['Predicted_Score']

    return results

# Dictionary to store results
all_results = {}

# Iterate through each dataset to show comparisons
for label, x_df, y_df in [
    (41, x41_data, y41_data), (32, x32_data, y32_data),
    (31, x31_data, y31_data), (22, x22_data, y22_data),
    (21, x21_data, y21_data), (12, x12_data, y12_data)
]:
    # Ensure the 'model' variable is correct for this label
    current_model, _ = run_model(x_df, y_df, label)
    table = get_predictions_table(x_df, y_df, label)
    print(f"\n--- Comparison Table for Model {label} (First 10 rows) ---")
    display(table.head(10))
    all_results[label] = table

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000029 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 274
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 12
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.129859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[106]	valid_0's rmse: 0.192535	valid_0's l2: 0.0370698
Model 41 - Actual Range: [11.93, 17.64] - Predicted Range: [12.42, 17.38]

--- Comparison Table for Model 41 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,12,21,22,31,32,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.51,16.35,16.48,16.26,16.28,16.397933,-0.117933
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.42,16.50,16.44,16.28,16.14,16.069109,0.070891
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,17.14,17.05,16.81,16.47,16.39,16.526289,-0.136289
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.39,13.31,12.98,12.74,12.94,13.301601,-0.361601
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.59,15.26,15.48,15.42,15.49,15.482561,0.007439
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,14.97,15.07,14.887123,0.182877
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.36,16.45,16.37,16.21,16.26,16.304301,-0.044301
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,16.19,15.88,16.08,15.96,15.97,15.935852,0.034148
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.72,12.83,13.15,13.19,13.11,12.832340,0.277660
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.52,15.07,15.16,14.85,14.71,14.815925,-0.105925

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000438 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 250
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 11
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.191831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[45]	valid_0's rmse: 0.214747	valid_0's l2: 0.0461161
Model 32 - Actual Range: [11.97, 17.67] - Predicted Range: [12.48, 17.33]

--- Comparison Table for Model 32 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,12,21,22,31,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.51,16.35,16.48,16.26,16.417243,-0.157243
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.42,16.50,16.44,16.28,16.217978,0.062022
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,17.14,17.05,16.81,16.47,16.669087,-0.199087
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.39,13.31,12.98,12.74,13.019875,-0.279875
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.59,15.26,15.48,15.42,15.358276,0.061724
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,14.97,15.020965,-0.050965
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.36,16.45,16.37,16.21,16.306589,-0.096589
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,16.19,15.88,16.08,15.96,15.933346,0.026654
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.72,12.83,13.15,13.19,13.588501,-0.398501
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.52,15.07,15.16,14.85,14.813149,0.036851

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000279 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 225
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 10
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.276620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[41]	valid_0's rmse: 0.165417	valid_0's l2: 0.0273629
Model 31 - Actual Range: [11.97, 17.72] - Predicted Range: [12.42, 17.58]

--- Comparison Table for Model 31 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,12,21,22,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.51,16.35,16.48,16.425806,0.054194
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.42,16.50,16.44,16.389777,0.050223
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,17.14,17.05,16.81,16.815692,-0.005692
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.39,13.31,12.98,12.797512,0.182488
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.59,15.26,15.48,15.507871,-0.027871
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.09,15.138695,-0.048695
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.36,16.45,16.37,16.418909,-0.048909
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,16.19,15.88,16.08,16.034415,0.045585
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.72,12.83,13.15,12.688677,0.461323
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.52,15.07,15.16,15.116507,0.043493

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004003 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 200
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 9
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.231549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[76]	valid_0's rmse: 0.252987	valid_0's l2: 0.0640025
Model 22 - Actual Range: [11.88, 17.63] - Predicted Range: [12.09, 17.52]

--- Comparison Table for Model 22 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,12,21,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.51,16.35,16.368992,-0.018992
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.42,16.50,16.271925,0.228075
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,17.14,17.05,16.727359,0.322641
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.39,13.31,12.460441,0.849559
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.59,15.26,15.470459,-0.210459
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.20,15.166166,0.033834
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.36,16.45,16.290557,0.159443
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,16.19,15.88,15.969972,-0.089972
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.72,12.83,12.845439,-0.015439
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.52,15.07,15.008093,0.061907

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014978 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 175
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 8
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.398451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[45]	valid_0's rmse: 0.227783	valid_0's l2: 0.0518851
Model 21 - Actual Range: [11.69, 17.76] - Predicted Range: [12.27, 17.70]

--- Comparison Table for Model 21 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,12,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.51,16.448572,0.061428
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.42,16.277875,0.142125
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,17.14,16.813000,0.327000
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.39,13.251820,0.138180
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.59,15.673103,-0.083103
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,15.36,15.418365,-0.058365
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.36,16.369773,-0.009773
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,16.19,16.208697,-0.018697
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.72,12.983136,-0.263136
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.52,15.965571,-0.445571

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033013 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 71, number of used features: 7
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 15.025916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 30 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[54]	valid_0's rmse: 0.510485	valid_0's l2: 0.260595
Model 12 - Actual Range: [10.69, 17.49] - Predicted Range: [12.09, 17.23]

--- Comparison Table for Model 12 (First 10 rows) ---

,معدل دیپلم,basic_science_avg,physiopathology_avg,clinical_avg,internship_avg,medical_course_type,11,Actual_Score,Predicted_Score,Difference
0,19.70,16.48,16.28,16.27,16.61,0.0,17.02,16.58,16.431530,0.148470
1,19.88,16.38,16.14,16.01,16.44,1.0,15.42,15.88,16.272084,-0.392084
2,19.93,16.79,16.39,16.25,16.62,1.0,16.68,16.60,16.896350,-0.296350
3,19.22,13.03,12.74,13.48,14.36,1.0,14.43,12.96,13.468054,-0.508054
4,19.84,15.47,15.49,15.83,16.28,1.0,14.47,15.34,15.120768,0.219232
5,19.71,15.09,15.00,14.92,15.45,1.0,15.21,15.06,14.972125,0.087875
6,19.95,16.36,16.26,16.40,16.76,0.0,17.25,15.87,16.481470,-0.611470
7,19.50,16.02,15.97,16.06,16.45,0.0,15.57,15.95,15.853064,0.096936
8,16.47,13.23,13.16,13.65,14.71,1.0,11.44,11.95,12.203323,-0.253323
9,17.60,15.12,14.71,14.96,15.68,0.0,16.19,16.03,15.996033,0.033967